routes/web.php
<?php
use App\Http\Controllers\Event\CardsController;
use App\Http\Controllers\Event\CheckinController;
use App\Http\Controllers\Event\EconomyController;
use App\Http\Controllers\Event\EventController;
use App\Http\Controllers\Event\FormController;
use App\Http\Controllers\Event\FormInputController;
use App\Http\Controllers\Event\PaymentController;
use App\Http\Controllers\Event\ResponseController;
use App\Http\Controllers\Event\Shop\BarcodeController;
use App\Http\Controllers\Event\Shop\ProductController;
use App\Http\Controllers\Event\Shop\ShopController;
use App\Http\Controllers\Event\SignupController;
use App\Http\Controllers\Event\UserEconomyController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController')->name('index');

Route::singleton('profile', ProfileController::class)->names('home');

Route::resource('events', EventController::class);
Route::prefix('events/{event}')->name('events.')->group(function () {
    Route::resource('checkin', CheckinController::class)->only(['index', 'create', 'store']);
    Route::resource('payments', PaymentController::class)->only(['index', 'create', 'store', 'destroy']);
    Route::singleton('signup', SignupController::class)->creatable()->except(['destroy', 'edit']);
    Route::resource('responses', ResponseController::class);

    Route::singleton('form', FormController::class)->creatable();
    Route::prefix('form')->name('form.')->group(function () {
        Route::resource('input', FormInputController::class)->except(['index']);
    });

    Route::get('cards', CardsController::class)->name('cards');
    Route::get('economy', EconomyController::class)->name('economy');
    Route::get('user_economy', UserEconomyController::class)->name('user_economy');

    // Event shop
    Route::controller(ShopController::class)->prefix('shop')->name('shop.')->group(function () {
        Route::get('', 'show')->name('show');
        Route::post('', 'enterBarcode');

        // Products
        Route::resource('products', ProductController::class);

        // Barcode list
        Route::get('barcodes', BarcodeController::class)->name('barcodes');
    });
});

Route::resource('users', UserController::class);
Route::resource('roles', RoleController::class);

Auth::routes(['verify' => true]);

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>{{ config('app.name', 'Application') }}</h1>
    <section>
        <p>
            Välkommen till MoS PLAN-portal! <br/>
            Skapa ett konto uppe till höger för att kunna registrera dig på våra arrangemang.
        </p>
        <p>
            Kontakta oss på
            <a href="mailto:info@mysochspel.se" target="_blank">info@mysochspel.se</a>
            om det är något du undrar över.
        </p>
        <h2>Arrangemangsinformation PLAN 2019</h2>
        <iframe src="https://docs.google.com/document/d/e/2PACX-1vQ0dSjzHFN4ODoWgC-0mcW0-Rcvr7Z4pCprj5bpjPoQvKdRE8XKHrbrMBzo6SVb42wimTyPF5S7uVUc/pub?embedded=true" style="width: 100%; border: 1px black solid; height: 40em;"></iframe> 
    </section>
@endsection

resources/views/role.blade.php
@extends('layouts.app')

@section('content_class', 'role')

@push('scripts')
    <script lang="javascript" type="text/javascript">
        function childChanged(container, checked) {
            var children = container.children('ul').children('li');
            var parent = container.parent().parent();
            var checkbox = container.children('input[type="checkbox"]');
            var checkbox_checked = checkbox.prop('checked');
            var checkbox_indeterminate = checkbox.prop('indeterminate');
            
            children.each(function() {
                return all_same = ($(this).children('input[type="checkbox"]').prop("checked") === checked);
            });
            console.log('All: '+all_same);
            
            if (all_same) {
                checkbox.prop({
                    'checked': checked,
                    'indeterminate': false
                });
            }
            else {
                checkbox.prop({
                    'checked': false,
                    'indeterminate': true
                });
            }
            
            if (checkbox.prop('checked') != checkbox_checked || checkbox.prop('indeterminate') != checkbox_indeterminate) {
                if (parent.is('li')) {
        			childChanged(parent, checked);
    			}
            }
        }
        
        $(document).ready(function() {
			console.log("Document ready");
			
			$(".tree li > i").click(function() {
    			console.log("click");
    			var li = $(this).parent();
    			if (li.hasClass('expanded')) {
        			li.removeClass('expanded');
                }
                else {
                    li.addClass('expanded');
                }
			});
			
			$('.tree input[type="checkbox"]').change(function(event) {
    			console.log("check");
    			var checked = $(this).prop('checked');
    			var container = $(this).parent();
    			var siblings = container.siblings();
    			var parent = container.parent().parent();
    			
    			// Check / Uncheck all children
    			container.find('input[type="checkbox"]').prop({
        			indeterminate: false,
                    checked: checked
    			});
    			
    			// Notify parent of change
    			if (parent.is('li')) {
        			childChanged(parent, checked);
    			}
			});
			
			$('form').submit(function(event) {
    			var checked = $('.tree input[type="checkbox"]').filter(function() {
                    return this.checked === true;
                });
                checked.parent().children('ul').find('input[type="checkbox"]').prop('checked', false);
			});
			
			// Check the checkboxes
			$('input[checked]').change();
		});
    </script>
@endpush

@section('content')
<h1>Editera roll</h1>
<h2>{{ $role->name }}</h2>

<form method="post" action="{{ route('roles.update', $role->id) }}">
    @csrf
    @method('PUT')
    <label for="name">Name</label>
    <input name="name" type="text" value="{{ $role->name }}"/>
    <label for="slug">Slug</label>
    <input name="slug" type="text" value="{{ $role->slug }}"/>
    <h3>Permissions</h3>
    <ul class="tree"><li class="expanded">
        <i></i>
        <input type="checkbox" name="permissions[]" value="*"
        @isset ($permissions->checked) checked @endisset />
        <label for="*">*</label>
        <ul>
            @foreach ($permissions->children as $name_1 => $permissions)
                <li>
                    @isset ($permissions->children)
                        <i></i>
                        <input type="checkbox" name="permissions[]" value="{{ $name_1 }}.*"
                        @isset ($permissions->checked) checked @endisset />
                        <label>{{ $name_1 }}</label>
                        <ul>
                            @foreach ($permissions->children as $name_2 => $permissions)
                                <li>
                                    @isset ($permissions->children)
                                        <i></i>
                                        <input type="checkbox" name="permissions[]" value="{{ $name_1 }}.{{ $name_2 }}.*"
                                        @isset ($permissions->checked) checked @endisset />
                                        <label>{{ $name_2 }}</label>
                                        <ul>
                                            @foreach ($permissions->children as $name_3 => $permissions)
                                                <li>
                                                    @isset ($permissions->children)
                                                        <i></i>
                                                        <input type="checkbox" name="permissions[]" value="{{ $name_1 }}.{{ $name_2 }}.{{ $name_3 }}.*"
                                                        @isset ($permissions->checked) checked @endisset
                                                        />
                                                        <label>{{ $name_3 }}</label>
                                                        <ul>
                                                            @foreach ($permissions->children as $name_4 => $permissions)
                                                                <li>
                                                                    @isset ($permissions->children)
                                                                        <i></i>
                                                                        <input type="checkbox" name="permissions[]" value="{{ $name_1 }}.{{ $name_2 }}.{{ $name_3 }}.{{ $name_4 }}.*"
                                                                        @isset ($permissions->checked) checked @endisset
                                                                        />
                                                                        <label>{{ $name_4 }}</label>
                                                                        <ul>
                                                                            
                                                                        </ul>
                                                                    @else
                                                                        <input type="checkbox" name="permissions[]" value="{{ $name_1 }}.{{ $name_2 }}.{{ $name_3 }}.{{ $name_4 }}.*"
                                                                        @isset ($permissions->checked) checked @endisset
                                                                        />
                                                                        <label>{{ $name_4 }}</label>
                                                                    @endisset
                                                                </li>
                                                            @endforeach
                                                        </ul>
                                                    @else
                                                        <input type="checkbox" name="permissions[]" value="{{ $name_1 }}.{{ $name_2 }}.{{ $name_3 }}"
                                                        @isset ($permissions->checked) 
                                                            checked
                                                        @endisset
                                                        />
                                                        <label>{{ $name_3 }}</label>
                                                    @endisset
                                                </li>
                                            @endforeach
                                        </ul>
                                    @else
                                        <input type="checkbox" name="permissions[]" value="{{ $name_1 }}.{{ $name_2 }}"
                                        @isset ($permissions->checked) checked @endisset
                                        />
                                        <label>{{ $name_2 }}</label>
                                    @endisset
                                </li>
                            @endforeach
                        </ul>
                    @else
                        <input type="checkbox" name="permissions[]" value="{{ $name_1 }}"
                        @isset ($permissions->checked) checked @endisset
                        />
                        <label>{{ $name_1 }}</label>
                    @endisset
                </li>
            @endforeach
        </ul>
    </li></ul>
    <input type="submit" value="Uppdatera" />
</form>

@endsection