routes/web.php
<?php
use App\Http\Controllers\Event\CardsController;
use App\Http\Controllers\Event\CheckinController;
use App\Http\Controllers\Event\EconomyController;
use App\Http\Controllers\Event\EventController;
use App\Http\Controllers\Event\FormController;
use App\Http\Controllers\Event\FormInputController;
use App\Http\Controllers\Event\PaymentController;
use App\Http\Controllers\Event\ResponseController;
use App\Http\Controllers\Event\Shop\BarcodeController;
use App\Http\Controllers\Event\Shop\ProductController;
use App\Http\Controllers\Event\Shop\ShopController;
use App\Http\Controllers\Event\SignupController;
use App\Http\Controllers\Event\UserEconomyController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController')->name('index');

Route::singleton('profile', ProfileController::class)->names('home');

Route::resource('events', EventController::class);
Route::prefix('events/{event}')->name('events.')->group(function () {
    Route::resource('checkin', CheckinController::class)->only(['index', 'create', 'store']);
    Route::resource('payments', PaymentController::class)->only(['index', 'create', 'store', 'destroy']);
    Route::singleton('signup', SignupController::class)->creatable()->except(['destroy', 'edit']);
    Route::resource('responses', ResponseController::class);

    Route::singleton('form', FormController::class)->creatable();
    Route::prefix('form')->name('form.')->group(function () {
        Route::resource('input', FormInputController::class)->except(['index']);
    });

    Route::get('cards', CardsController::class)->name('cards');
    Route::get('economy', EconomyController::class)->name('economy');
    Route::get('user_economy', UserEconomyController::class)->name('user_economy');

    // Event shop
    Route::controller(ShopController::class)->prefix('shop')->name('shop.')->group(function () {
        Route::get('', 'show')->name('show');
        Route::post('', 'enterBarcode');

        // Products
        Route::resource('products', ProductController::class);

        // Barcode list
        Route::get('barcodes', BarcodeController::class)->name('barcodes');
    });
});

Route::resource('users', UserController::class);
Route::resource('roles', RoleController::class);

Auth::routes(['verify' => true]);

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Event\Registration\Response;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'ssn',
        'phone1',
        'phone2',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'last_renewed' => 'date',
    ];

    /**
    * The events that the user has signed up to
    */
    public function events()
    {
        return $this->belongsToMany(Event::class)->withPivot('barcode_id');
    }

    public function eventSeats()
    {
        return $this->belongsTo(EventSeat::class);
    }

    public function purchases()
    {
        return $this->hasMany(Purchase::class);
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function eventRegistrations()
    {
        return $this->hasMany(Response::class);
    }

    public function hasRole(string $roleSlug): bool
    {
        return $this->roles()->where('slug', $roleSlug)->count() == 1;
    }

    public function isAdmin(): bool
    {
        return $this->hasRole('admin');
    }

    public function hasAccess(string $permission): bool
    {
        foreach($this->roles as $role) {
            if ($role->hasAccess($permission)) return true;
        }
        return false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
    }

    public function index()
    {
        $this->authorize('list', User::class);

        $users = User::get();

        $table = (object)[];
        $table->headers = [
            'Id',
            'Namn',
            'Epost',
            'Personnummer',
            'Telefon',
            'Alt. telefon',
            'Senast medlemsreg.',
            'Registrering'
        ];
        $table->rows = [];
        foreach ($users as $user) {
            $row = [];
            $id_cell = (object)[];
            $id_cell->link = route('users.show', $user->id);
            $id_cell->value = $user->id;
            $row[] = $id_cell;
            $row[] = $user->name;
            $row[] = $user->email;
            $row[] = $user->ssn;
            $row[] = $user->phone1;
            $row[] = $user->phone2;
            $row[] = $user->last_renewed;
            $row[] = $user->created_at;
            $table->rows[] = $row;
        }

        $header = "Användare";

        return view('general.table')
            ->with('header', $header)
            ->with('table', $table);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        //

    }

    public function store(Request $request)
    {
        //
    }
    public function show(User $user)
    {
        $this->authorize('view', $user);

        return view('user.show')
            ->with('user', $user);
    }

    public function edit(User $user)
    {
        $this->authorize('update', $user);

        if (Gate::allows('roles', $user)) {
            $roles = Role::get();

            return view('user.edit')
            ->with('user', $user)
            ->with('roles', $roles);

        }

        return view('user.edit')
            ->with('user', $user);
    }

    public function update(Request $request, User $user)
    {
        // Authorize request
        $this->authorize('update', $user);

        // Validate request
        $validated = $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'roles' => 'array'
        ]);

        if (isset($validated['roles'])) {
            // Setup new roles
            $new_roles = $validated['roles'];

            // Remove already associated roles
            foreach($user->roles as $role) {
                if (in_array($role->id, $new_roles)) {
                    unset($new_roles[$role->id]);
                }
                else {
                    $user->roles()->detach($role->id);
                }
            }

            // Add missing roles
            foreach ($new_roles as $role) {
                $user->roles()->attach($role);
            }

        }

        $user->name = $validated['name'];
        $user->email = $validated['email'];

        $user->save();

        if ($user->id == Auth::user()->id) {
            return redirect(route('home.index'));
        }

        return redirect(route('users.index'));
    }

    public function destroy(User $user)
    {
        $this->authorize('delete', $user);

        $user->delete();

        if ($user->id == Auth::user()->id) {
            Auth::logout();
            return redirect(route('index'));
        }

        return redirect(route('users.index'));
    }
}

resources/views/user/dashboard.blade.php
@extends('layouts.app')

@section('content_class', 'event_info')

@section('content')
    <h1>Din profil</h1>

    <div id="info">
        <span class="label">Namn:</span>
        <span class="value">{{ $user->name }}</span>
        <span class="label">E-post:</span>
        <span class="value">{{ $user->email }}</span>
        <span class="label">Uppdaterade medlemskap:</span>
        <span class="value">{{ \Carbon\Carbon::parse($user->last_renewed)->format('d M Y') }}</span>
        <a class="button" href="{{ route('home.edit') }}">Redigera</a>
        <form action="{{ route('users.destroy', $user->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <input type="submit" value="Radera" class="button"  onclick="return confirm('Are you sure?')" style="color: red"/>
        </form>
    </div>

    @isset($event)
        <h2>Aktuellt arrangemang: <a href="{{ route('events.show', $event->uri) }}">{{ $event->name }}</a></h2>

        @isset($user_economy)
            <h3>Din ekonomi</h3>
            <div class="label_value">
                <span class="label">Entrékostnad:</span>
                <span class="value">{{ $user_economy->entry_price }}kr</span>
                <span class="label">Tilläggskostnader:</span>
                <span class="value">{{ $user_economy->event_extra }}kr</span>
                <span class="label"><a href="{{ route('home.purchases') }}">Spenderat i butik</a>:</span>
                <span class="value">{{ $user_economy->event_purchases }}kr</span>
                <hr />
                <span class="label">Betalat: </span>
                <span class="value">{{ $user_economy->payed }}kr</span>
                <span class="label">Aktuell skuld: </span>
                <span class="value">{{ $user_economy->debt }}kr</span>
            </div>
        @else
            <p>Du har inte registrerat dig ännu</p>
        @endisset
    @else
        <h2>Inget aktuellt arrangemang</h2>
    @endisset

@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content_class', 'form')

@section('content')
<h1>Redigera användare</h1>

<form action="{{ route('users.update', $user->id) }}" method="POST">
    @csrf
    @method('PUT')

    <label for="name">Namn</label>
    <input id="name" name="name" type="text" value="{{ $user->name }}" />

    <label for="email">Epost</label>
    <input id="email" name="email" type="email" value="{{ $user->email }}" />

    @isset ($roles)
    <fieldset>
        <legend>Roles:</legend>

        @foreach ($roles as $role)
            <input name="roles[{{ $role->id }}]" value="{{ $role->id }}" type="checkbox" {{ $user->hasRole($role->slug) ? 'checked' : '' }}>
            <label for="{{ $role->slug }}">{{ $role->name }}</label>
            <br/>
        @endforeach
    </fieldset>
    @endisset

    <input type="submit"  value="Uppdatera"/>

</form>

@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content_class', 'event_info')

@section('content')
    <h1>{{ $user->name }}</h1>
    <div id="info">
        <span class="label">E-post:</span>
        <span class="value">{{ $user->email }}</span>
        <span class="label">Personnummer:</span>
        <span class="value">{{ $user->ssn }}</span>
        <span class="label">Telefonnummer:</span>
        <span class="value">{{ $user->phone1 }}</span>
        <span class="label">Kontot skapades:</span>
        <span class="value">{{ \Carbon\Carbon::parse($user->created_at)->format('d M Y, H:i') }}</span>
        <span class="label">Kontot uppdaterades:</span>
        <span class="value">{{ \Carbon\Carbon::parse($user->updated_at)->format('d M Y, H:i') }}</span>
        <span class="label">Uppdaterade medlemskap:</span>
        <span class="value">{{ \Carbon\Carbon::parse($user->last_renewed)->format('d M Y') }}</span>
        <a class="button" href="{{ route('users.edit', $user->id) }}">Redigera</a>
        <form action="{{ route('users.destroy', $user->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <input type="submit" value="Radera" class="button"  onclick="return confirm('Are you sure?')" style="color: red"/>
        </form>
    </div>
@endsection