routes/web.php
<?php
use App\Http\Controllers\Event\CardsController;
use App\Http\Controllers\Event\CheckinController;
use App\Http\Controllers\Event\EconomyController;
use App\Http\Controllers\Event\EventController;
use App\Http\Controllers\Event\FormController;
use App\Http\Controllers\Event\FormInputController;
use App\Http\Controllers\Event\PaymentController;
use App\Http\Controllers\Event\ResponseController;
use App\Http\Controllers\Event\Shop\BarcodeController;
use App\Http\Controllers\Event\Shop\ProductController;
use App\Http\Controllers\Event\Shop\ShopController;
use App\Http\Controllers\Event\SignupController;
use App\Http\Controllers\Event\UserEconomyController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController')->name('index');

Route::singleton('profile', ProfileController::class)->names('home');

Route::resource('events', EventController::class);
Route::prefix('events/{event}')->name('events.')->group(function () {
    Route::resource('checkin', CheckinController::class)->only(['index', 'create', 'store']);
    Route::resource('payments', PaymentController::class)->only(['index', 'create', 'store', 'destroy']);
    Route::singleton('signup', SignupController::class)->creatable()->except(['destroy', 'edit']);
    Route::resource('responses', ResponseController::class);

    Route::singleton('form', FormController::class)->creatable();
    Route::prefix('form')->name('form.')->group(function () {
        Route::resource('input', FormInputController::class)->except(['index']);
    });

    Route::get('cards', CardsController::class)->name('cards');
    Route::get('economy', EconomyController::class)->name('economy');
    Route::get('user_economy', UserEconomyController::class)->name('user_economy');

    // Event shop
    Route::controller(ShopController::class)->prefix('shop')->name('shop.')->group(function () {
        Route::get('', 'show')->name('show');
        Route::post('', 'enterBarcode');

        // Products
        Route::resource('products', ProductController::class);

        // Barcode list
        Route::get('barcodes', BarcodeController::class)->name('barcodes');
    });
});

Route::resource('users', UserController::class);
Route::resource('roles', RoleController::class);

Auth::routes(['verify' => true]);

app/Http/Controllers/Event/CardsController.php
<?php

namespace App\Http\Controllers\Event;

use Validator;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Controller;
use App\Models\Event;

class CardsController extends Controller
{
    
    public function __invoke(Request $request, Event $event)
    {
        // Auth
        $this->authorize('list', [Response::class, $event]);
        
        $card_count = intval($request->input('cards', 0));
        
        // Get form and responses
        $form = $event->registrationForm;
        $responses = $form->responses;
        
        // Get the inputs which should be display on card
        $inputs_boxes = $form->inputs()->where('type', 'checkbox')->where('oncard', true)->get();
        
        // Track max barcode
        $max_barcode_id = 0;
        
        $cards = [];
        
        // Create cards for each of the responses
        foreach ($responses as $response) {
            $user = $response->user;
            
            $event_relation = $user->events()->where('event_id', $event->id)->first();
            if ($event_relation == null) continue; // Should not happen
            
            $barcode_id = $event_relation->pivot->barcode_id;
            $barcode = $event->barcode_prefix . sprintf('%03d', $barcode_id);
            $max_barcode_id = $barcode_id > $max_barcode_id ? $barcode_id : $max_barcode_id;
            
            $boxes = [];
            
            foreach ($inputs_boxes as $input) {
                $response_value = $response->values()->where('input_id', $input->id)->first();
                $box = (object)[];
                $box->checked = $response_value != null ? $response_value->value == 'on' ? true : false : false;
                $box->label = $input->label;
                $boxes[] = $box;
            }
            
            $card = (object)[];
            
            $card->username = $user->name;
            $card->barcode = $barcode;
            $card->boxes = $boxes;
            
            $cards[] = $card;
            $card_count--;
        }
        
        $barcode_id = $max_barcode_id+1;
        
        while ($card_count > 0) {
            $boxes = [];
            
            $barcode = $event->barcode_prefix . sprintf('%03d', $barcode_id++);
            
            foreach ($inputs_boxes as $input) {
                $response_value = $response->values()->where('input_id', $input->id)->first();
                $box = (object)[];
                $box->checked = false;
                $box->label = $input->label;
                $boxes[] = $box;
            }
            
            $card = (object)[];
            
            $card->username = "_";
            $card->barcode = $barcode;
            $card->boxes = $boxes;
            
            $cards[] = $card;
            $card_count--;
        }
        
        //var_dump($cards);
        
        return view('event.cards')
            ->with('cards', $cards);
    }
    
}

app/Http/Controllers/Event/CheckinController.php
<?php

namespace App\Http\Controllers\Event;

use Validator;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\MessageBag;

use App\Http\Controllers\Controller;
use App\Models\Checkin;
use App\Models\Event;
use App\Models\ViewCheckinStatus;
use App\Models\ViewUserEconomy;

class CheckinController extends Controller
{
    
    public function index(Event $event)
    {
        // Auth
        $this->authorize('list', [Checkin::class, $event]);
        
        $checkin_statuses = ViewCheckinStatus::where('event_id', $event->id)->get();
        
        $table = (object)[];
        $table->headers = ['Användare', 'Status', 'Senast ändrad'];
        $table->rows = [];
        
        foreach ($checkin_statuses as $status) {
            $row = [];
            $row[] = $status->user->name;
            $row[] = $status->check_in ? 'Inckeckad' : 'Utcheckad';
            $row[] = $status->time;
            $table->rows[] = $row;
        }
        
        $header = "Incheckningsstatus för {$event->name}";
        
        $adminbar = [];
        if (Auth::user()->can('create', [Checkin::class, $event]))
            $adminbar['Incheckining'] = route('events.checkin.create', $event);
        
        return view('general.table')
            ->with('table', $table)
            ->with('header', $header)
            ->with('adminbar', $adminbar);
    }
    
    public function create(Event $event)
    {
        // Auth
        $this->authorize('create', [Checkin::class, $event]);
        
        return view('event.checkin')
            ->with('event', $event);
    }
    
    public function store(Request $request, Event $event)
    {
        // Auth
        $this->authorize('create', [Checkin::class, $event]);
        
        $prefix = preg_quote($event->barcode_prefix);
        
        // Validate request
        $validated = $request->validate([
            'barcode' => "regex:/^(?i)$prefix([0-9]+)/"
        ]);
        
        preg_match("/^(?i)$prefix([0-9]+)/", $validated['barcode'], $matches);
        
        // Get user based on barcode
        $user = $event->users()->wherePivot('barcode_id', $matches[1])->first();
        
        if (! $user) {
            $errors = new MessageBag();
            $errors->add('barcode', 'User not found');
            return view('event.checkin')
                ->with('event', $event)
                ->withErrors($errors);
        }
        
        $status = Checkin::getStatus($event, $user);
        $new_status = ($status+1) % 2;
        
        // Create new event
        $checkin = new Checkin;
        $checkin->user()->associate($user);
        $checkin->event()->associate($event);
        $checkin->check_in = $new_status;
        $checkin->save();
        
        // Get debt
        $debt = ViewUserEconomy::where([
                'user_id' =>  $user->id,
                'event_id' => $event->id
        ])->first()->debt;
        
        
        return view('event.checkin')
            ->with('event', $event)
            ->with('user', $user)
            ->with('first_checkin', $status===null)
            ->with('status', $new_status)
            ->with('debt' , $debt);
    }
}

app/Http/Controllers/Event/EconomyController.php
<?php

namespace App\Http\Controllers\Event;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Event;

class EconomyController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
    }
    
    /**
     * Handle the incoming request.
     */
    public function __invoke(Event $event)
    {
        // Authorize
        $this->authorize('list', [Purchase::class, $event]);
        
        $responses = $event->registrationForm?->responses ?? array();
        
        // Generate table
        $table = (object)[];
        
        $table->headers = [
            'Produkt', 'Pris', 'Antal', 'Summa'
        ];
        
        $sum_row = ['TOTAL SUMMA', '', '', 0];
        
        // Entry cost
        $entry_cost_row = [];
        $entry_cost_row[] = 'Entrékostnad';
        $entry_cost_row[] = $event->entry_price . ' kr';
        $entry_cost_row[] = count($responses);
        $entry_cost_row[] = count($responses) * $event->entry_price . ' kr';
        $table->rows[] = $entry_cost_row;
        
        $sum_row[3] += count($responses) * $event->entry_price;
        
        // Add space
        $table->rows[] = ['', '', '', ''];
        
        // Extra event options
        $sub_sum_row = ['SUMMA Extra', '', 0, 0];
        $inputs = $event->registrationForm?->inputs()->where('price', '>', '0')->get() ?? [];
        foreach ($inputs as $input) {
            $row = [];
            $row[0] = $input->label;
            $row[1] = $input->price . ' kr';
            $count = 0;
            foreach ($responses as $response) {
                $count += $response->values()->where('input_id', $input->id)->count();
            }
            $row[2] = $count;
            $row[3] = $count * $input->price . ' kr';
            
            // Add to sum row
            $sub_sum_row[2] += $count;
            $sub_sum_row[3] += $count * $input->price;
            
            $table->rows[] = $row;
        }
        $sum_row[3] += $sub_sum_row[3];
        $sub_sum_row[3] .= ' kr';
        $table->rows[] = $sub_sum_row;
        
        // Add space
        $table->rows[] = ['', '', '', ''];
        
        // Purcahses
        $sub_sum_row = ['SUMMA Köp', '', 0, 0];
        foreach($event->products as $product) {
            $row = [];
            $row[0] = $product->name;
            $row[1] = $product->price . ' kr';
            $count = 0;
            foreach ($product->purchases as $purcahse) {
                $count += $purcahse->pivot->amount;
            }
            $row[2] = $count;
            $row[3] = $count * $product->price . ' kr';
            
            // Add to sum row
            $sub_sum_row[2] += $count;
            $sub_sum_row[3] += $count * $product->price;
            
            $table->rows[] = $row;
        }
        $sum_row[3] += $sub_sum_row[3];
        $sub_sum_row[3] .= ' kr';
        $table->rows[] = $sub_sum_row;
        
        // Add space
        $table->rows[] = ['', '', '', ''];
        
        // SUM
        $sum_row[3] .= ' kr';
        $table->rows[] = $sum_row;
        
        //Heading
        $header = "Inkomster under {$event->name}";
        
        return view('general.table')
            ->with('table', $table)
            ->with('header', $header);
    }
}

app/Http/Controllers/Event/FormController.php
<?php

namespace App\Http\Controllers\Event;

use App\Http\Controllers\Controller;
use App\Models\Event;
use App\Models\Event\Registration\Form;
use App\Models\Event\Registration\FormInput;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;

class FormController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
    }

    private function createForm($action, Event $event): object
    {
        $form = $event->form;
        $formData = (object) [
            'action' => route("events.form.$action", $event),
            'inputs' => [
                (object)[
                    'name' => 'registration_opens_at',
                    'label' => __('event.form.registration_opens_at'),
                    'type' => 'datetime-local',
                    'max' => '9999-12-31T23:59:59',
                    'required' => false,
                    'value' => $form?->registration_opens_at,
                ],
                (object)[
                    'name' => 'registration_closes_at',
                    'label' => __('event.form.registration_closes_at'),
                    'type' => 'datetime-local',
                    'max' => '9999-12-31T23:59:59',
                    'required' => false,
                    'value' => $form?->registration_closes_at,
                ],
                (object)[
                    'name' => '',
                    'type' => 'submit',
                    'value' => __("form.$action"),
                ],
            ]
        ];
        if ($action == 'update') {
            $formData->method = 'PATCH';
        }
        return $formData;
    }

    private function createInputTable(?Form $form): object {
        $table = (object) [];
        $attributes = new Collection((new FormInput())->getFillable());

        $table->headers = $attributes->map(
            fn($attribute) => __("event.form.input.$attribute")
        );

        $table->rows = $form?->inputs->map(
            fn($input) => $attributes->map(
                fn($attribute) => $input->getAttributeValue($attribute)
            )
        );

        return $table;
    }

    /**
     * Show the form for creating a new resource.
     * @throws AuthorizationException
     */
    public function create(Event $event)
    {
        $this->authorize('create', [Form::class, $event]);

        $title = __( 'event.form.create');
        $form = $this->createForm('store', $event);

        return view('general.form')
            ->with('title', $title)
            ->with('form', $form);
    }

    /**
     * Store a newly created resource in storage.
     * @throws AuthorizationException
     */
    public function store(Request $request, Event $event)
    {
        $this->authorize('create', [Form::class, $event]);

        $validated = $request->validate([
            'registration_opens_at' => 'nullable|date',
            'registration_closes_at' => 'nullable|date',
        ]);

        $event->form()->create($validated);

        return redirect(route('events.form.show', $event));
    }

    /**
     * Display the specified resource.
     * @throws AuthorizationException
     */
    public function show(Event $event)
    {
        $this->authorize('view', [Form::class, $event]);

        $form = $event->form;

        $adminbar = null;
        $user = Auth::user();
        if ($form) {
            if ($user->can('update', $form)) {
                $adminbar[__('event.form.edit')] = route('events.form.edit', $event);
            }
            if ($user->can('update', $form)) {
                $adminbar[__('event.form.input.create')] = route('events.form.input.create', $event);
            }
        } else {
            if ($user->can('create', [Form::class, $event])) {
                $adminbar[__('event.form.create')] = route('events.form.create', $event);
            }
        }

        $table = $this->createInputTable($form);

        return view('event.form.show')
            ->with('adminbar', $adminbar)
            ->with('event', $event)
            ->with('form', $form)
            ->with('table', $table);
    }

    /**
     * Show the form for editing the specified resource.
     * @throws AuthorizationException
     */
    public function edit(Event $event)
    {
        $this->authorize('update', $event->form);

        $title = __( 'event.form.edit');
        $form = $this->createForm('update', $event);

        return view('general.form')
            ->with('title', $title)
            ->with('form', $form);
    }

    /**
     * Update the specified resource in storage.
     * @throws AuthorizationException
     */
    public function update(Request $request, Event $event)
    {
        $this->authorize('update', $event->form);

        $validated = $request->validate([
            'registration_opens_at' => 'nullable|date',
            'registration_closes_at' => 'nullable|date',
        ]);

        $event->form()->update($validated);

        return redirect(route('events.form.show', $event));
    }

    /**
     * Remove the specified resource from storage.
     * @throws AuthorizationException
     */
    public function destroy(Event $event)
    {
        $this->authorize('delete', $event->form);
    }
}

resources/views/event/cards.blade.php
@extends('layouts.app')

@section('content_class', 'cards')

@section('header', '')

@push('scripts')
    <script src="{{ asset('js/jquery.textfill.min.js') }}" lang="javascript" type="text/javascript"></script>@push('scripts')
    <script src="{{ asset('js/JsBarcode.all.min.js') }}"></script>
@endpush
    <script lang="javascript" type="text/javascript">
        $(document).ready(function() {
            // Generate barcodes
            JsBarcode("svg.barcode").init();
            
            // Make sure the names fit
			$(".card .name").textfill({
				debug: true,
				widthOnly: true
			});
		});
    </script>
@endpush

@section('content')
    @foreach ($cards as $card)
        <div class="card">
            <div class="name">
                <span>{{ $card->username }}</span>
            </div>
            <div class="barcode">
                <svg 
                    class="barcode"
                    jsbarcode-height="160"
                    jsbarcode-value="{{ $card->barcode }}"
                ></svg>
            </div>
            <div><div class="boxes">
                @foreach ($card->boxes as $box)
				    <span class="box{{ $box->checked ? ' checked' : '' }}"></span>
				    <span>{{ $box->label }}</span>
                @endforeach
			</div></div>
        </div>
    @endforeach
@endsection

resources/views/event/checkin.blade.php
@extends('layouts.app')

@section('header', '')

@section('content_class', 'checkin')

@section('content')
    <script type="text/javascript" lang="javascript">
        $(document).ready(function() {
            setTimeout(function() {
                $("#notice").hide(
                        "fade", 
                        2000, 
                        function() {
                    $(this).remove();
                });
            }, 2000);
        });
    </script>
    
    <h1>Checkin - {{ $event->name }}</h1>
    @if ($errors->any())
        <div id="notice">
            <h1 class="red">Error</h1>
            @foreach ($errors->all() as $error)
                <h2 class="red">{{ $error }}</h2>
            @endforeach
        </div>
    @else 
        @isset ($status)
            <div id="notice">
                <h1>{{ $user->name }}</h1>
                @if ($first_checkin)
                    <h2 class="green">Välkommen till {{ $event->name }}</h2>
                @else
                    @switch($status)
                        @case(0)
                            <h2 class="red">Hejdå, välkommen åter</h2>
                            @break
                        @case(1)
                            <h2 class="green">Välkommen tillbaka</h2>
                            @break
                        @default
                            <h2 class="red">Error: Konstig status</h2>
                    @endswitch
                @endif
                <h2 class="red">Aktuell skuld: {{ $debt }}</h2>
            </div>
        @endisset
    @endif
    
    <form action="{{ route('events.checkin.store', $event) }}" method="POST">
        @csrf
        
        <label for="barcode">Barcode</label>
        <input id="barcode" name="barcode" type="text" autofocus/>
        
        <input type="submit" value="Checkin" />
    </form>
@endsection

resources/views/event/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1>Edit Event</h1>
    
    <form action="{{ route('events.update', $event->uri) }}" method="post">
        @csrf
        @method('PUT')
        
        @if ($errors->has('uri'))
            <span class="error">
                {{ $errors->first('uri') }}
            </span>
        @endif
        <label for="uri">URI</label>
        <input id="uri" name="uri" type="text" value="{{ $event->uri }}"/>
        
        <label for="name">Name</label>
        <input id="name" name="name" type="text" value="{{ $event->name }}"/>
        
        <label for="start_time">Start Time</label>
        <input id="start_time" name="start_time" type="datetime" value="{{ $event->start_time }}"/>
        
        <label for="end_time">End Time</label>
        <input id="end_time" name="end_time" type="datetime" value="{{ $event->end_time }}"/>
        
        <label for="entry_price">Entry Price</label>
        <input id="entry_price" name="entry_price" type="number" value="{{ $event->entry_price }}"/>
        
        <label for="max_seats">Max Seats</label>
        <input id="max_seats" name="max_seats" type="number" value="{{ $event->max_seats }}"/>
        
        <label for="barcode_prefix">Barcode Prefix</label>
        <input id="barcode_prefix" name="barcode_prefix" type="text" value="{{ $event->barcode_prefix }}"/>
        
        <label for="max_debt">Max Debt</label>
        <input id="max_debt" name="max_debt" type="number" value="{{ $event->max_debt }}"/>
        
        <label for="description">Description</label>
        <textarea id="description" name="description"> {{ $event->description }} </textarea>
        
        <input type="submit" value="Update" />
    </form>
@endsection

resources/views/event/event.blade.php
@extends('layouts.app')

@section('content_class', 'event_info')

@section('content')
    <h1>{{ $event->name }}</h1>
    <div id="info">
        @switch ($event->registrationAvailablity())
            @case (-1)
                <span class="label error">Registrering är tillgänglig från: </span>
                <span class="value error">{{ $event->registrationForm->registration_opens_at }}</span>
                @break
            @case (0)
                <span class="label">Registreringen är öppen:</span>
                <a class="value" href="{{ route('events.signup', $event) }}">
                    Registrera dig nu!
                </a>
                @break
            @case (1)
                <span class="label error">Registreringen stängde:</span>
                <span class="value error">{{ $event->registrationForm->registration_closes_at }}</span>
                @break
        @endswitch
        <span class="label">Entrépris:</span>
        <span class="value">{{ $event->entry_price }}kr</span>
        <span class="label">Start:</span>
        <span class="value">{{ \Carbon\Carbon::parse($event->start_time)->format('d M Y, H:i') }}</span>
        <span class="label">Slut:</span>
        <span class="value">{{ \Carbon\Carbon::parse($event->end_time)->format('d M Y, H:i') }}</span>
    </div>
    <div id="description">
        {!! $event->description !!}
    </div>
@endsection

resources/views/event/registration_new.blade.php
@extends('layouts.app')

@section('content_class', 'registration')

@section('content')
<h1>Ny registrering för {{ $event_name }}</h1>
@if ($inputs == NULL)
    
    <h2>Registrering är inte tillgänglig</h2>
    
    @if($form_errors->any())
        @foreach($form_errors->all() as $error)
            <p class="error">{{ $error }}</p>
        @endforeach
    @endif
    
@else 
    
    @if($form_errors->any())
        @foreach($form_errors->all() as $error)
            <p class="error">{{ $error }}</p>
        @endforeach
    @endif
    
    <h2>Entrépris: {{ $event_price }}kr</h2>
    
    <form action="{{$form_action}}" method="POST">
        @csrf
        
        <label for="user">Användare</label>
        <select id="user" name="user">
            @foreach ($users as $user)
                <option value="{{ $user->id }}">{{ $user->name }}</option>
            @endforeach
        </select>
        
        @foreach ($inputs as $input)
            @if($input->type == 'textarea')
                <label for="{{ $input->name }}" style="justify-self: left">
                    {{ $input->label }}
                </label>
                <textarea 
                    name="{{ $input->name }}"
                    placeholder="{{ $input->placeholder }}"
                    {{ $input->disabled }}
                >{{ $input->value }}</textarea>
            @elseif ($input->type == 'checkbox')
                <label for="{{ $input->name }}">
                    {{ $input->label }}
                    @isset ($input->price)
                        ({{ $input->price }}kr)
                    @endisset
                </label>
                <input
                    type="checkbox"
                    name="{{ $input->name }}"
                    placeholder="{{ $input->placeholder }}"
                    @if ($input->value == 'on') checked @endif
                    {{ $input->disabled }}
                />
            @else
                <label for="{{ $input->name }}">
                    {{ $input->label }}
                    @isset ($input->price)
                        ({{ $input->price }}kr)
                    @endisset
                </label>
                <input
                    type="{{ $input->type }}"
                    name="{{ $input->name }}"
                    placeholder="{{ $input->placeholder }}"
                    value="{{ $input->value }}"
                    {{ $input->disabled }}
                />
            @endif
        @endforeach
        
        <input type="submit" value="Registrera"/>
    </form>
    
@endif
@endsection

resources/views/event/signup.blade.php
@extends('layouts.app')

@section('content_class', 'registration')

@section('content')
<h1>Anmälan för {{ $event_name }}</h1>
@if ($inputs == NULL)
    
    <h2>Registrering är inte tillgänglig</h2>
    
    @if($form_errors->any())
        @foreach($form_errors->all() as $error)
            <p class="error">{{ $error }}</p>
        @endforeach
    @endif
    
@else 
    
    @if($form_errors->any())
        @foreach($form_errors->all() as $error)
            <p class="error">{{ $error }}</p>
        @endforeach
    @endif
    
    <h2>Entrépris: {{ $event_price }}kr</h2>
    
    <form action="" method="POST">
        @csrf
        
        @isset ($editing) @method('PUT') @endisset
        
        @foreach ($inputs as $input)
            @if($input->type == 'textarea')
                <label for="{{ $input->name }}" style="justify-self: left">
                    {{ $input->label }}
                </label>
                <textarea 
                    name="{{ $input->name }}"
                    placeholder="{{ $input->placeholder }}"
                    {{ $input->disabled }}
                >{{ $input->value }}</textarea>
            @elseif ($input->type == 'checkbox')
                <label for="{{ $input->name }}">
                    {{ $input->label }}
                    @isset ($input->price)
                        ({{ $input->price }}kr)
                    @endisset
                </label>
                <input
                    type="checkbox"
                    name="{{ $input->name }}"
                    placeholder="{{ $input->placeholder }}"
                    @if ($input->value == 'on') checked @endif
                    {{ $input->disabled }}
                />
            @else
                <label for="{{ $input->name }}">
                    {{ $input->label }}
                    @isset ($input->price)
                        ({{ $input->price }}kr)
                    @endisset
                </label>
                <input
                    type="{{ $input->type }}"
                    name="{{ $input->name }}"
                    placeholder="{{ $input->placeholder }}"
                    value="{{ $input->value }}"
                    {{ $input->disabled }}
                />
            @endif
        @endforeach
        <label for="policy">Jag godkänner att mina uppgifter hanteras av MoS</label>
        <input id="policy" name="policy" type="checkbox" required />
        
        @isset ($editing)
            <input type="submit" value="Uppdatera"/>
        @else
            <input type="submit" value="Registrera"/>
        @endisset
    </form>
    
@endif
@endsection